# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StackedGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_guif_main(object):
    def setupUi(self, guif_main):
        guif_main.setObjectName("guif_main")
        guif_main.resize(873, 817)
        guif_main.setWindowOpacity(1.0)
        self.guif_main_wid = QtWidgets.QWidget(guif_main)
        self.guif_main_wid.setObjectName("guif_main_wid")
        self.gridLayout = QtWidgets.QGridLayout(self.guif_main_wid)
        self.gridLayout.setObjectName("gridLayout")
        self.guif_main_grid = QtWidgets.QWidget(self.guif_main_wid)
        self.guif_main_grid.setObjectName("guif_main_grid")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.guif_main_grid)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.guif_mm_stacker = QtWidgets.QStackedWidget(self.guif_main_grid)
        self.guif_mm_stacker.setObjectName("guif_mm_stacker")
        self.guif_mainmenu = QtWidgets.QWidget()
        self.guif_mainmenu.setObjectName("guif_mainmenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.guif_mainmenu)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.guif_mm_grid = QtWidgets.QGridLayout()
        self.guif_mm_grid.setObjectName("guif_mm_grid")
        self.guif_mm_grid_btn = QtWidgets.QHBoxLayout()
        self.guif_mm_grid_btn.setObjectName("guif_mm_grid_btn")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.guif_mm_grid_btn.addItem(spacerItem)
        self.guif_mm_btn_login = QtWidgets.QPushButton(self.guif_mainmenu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.guif_mm_btn_login.setFont(font)
        self.guif_mm_btn_login.setObjectName("guif_mm_btn_login")
        self.guif_mm_btn_login.clicked.connect(self.call_logmenu)
        self.guif_mm_grid_btn.addWidget(self.guif_mm_btn_login)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.guif_mm_grid_btn.addItem(spacerItem1)
        self.guif_mm_btn_reg = QtWidgets.QPushButton(self.guif_mainmenu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.guif_mm_btn_reg.setFont(font)
        self.guif_mm_btn_reg.setObjectName("guif_mm_btn_reg")
        self.guif_mm_grid_btn.addWidget(self.guif_mm_btn_reg)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.guif_mm_grid_btn.addItem(spacerItem2)
        self.guif_mm_grid.addLayout(self.guif_mm_grid_btn, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.guif_mm_grid.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.guif_mm_grid.addItem(spacerItem4, 0, 0, 1, 1)
        self.guif_mm_title = QtWidgets.QLabel(self.guif_mainmenu)
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.guif_mm_title.setFont(font)
        self.guif_mm_title.setAlignment(QtCore.Qt.AlignCenter)
        self.guif_mm_title.setObjectName("guif_mm_title")
        self.guif_mm_grid.addWidget(self.guif_mm_title, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.guif_mm_grid.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.guif_mm_grid, 1, 0, 1, 1)
        self.guif_mm_stacker.addWidget(self.guif_mainmenu)
        self.guif_loginmenu = QtWidgets.QWidget()
        self.guif_loginmenu.setObjectName("guif_loginmenu")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.guif_loginmenu)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.guif_lm_grid = QtWidgets.QGridLayout()
        self.guif_lm_grid.setObjectName("guif_lm_grid")
        self.guif_lm_title_logo = QtWidgets.QLabel(self.guif_loginmenu)
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.guif_lm_title_logo.setFont(font)
        self.guif_lm_title_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.guif_lm_title_logo.setObjectName("guif_lm_title_logo")
        self.guif_lm_grid.addWidget(self.guif_lm_title_logo, 0, 0, 1, 1)
        self.guif_lm_title_login = QtWidgets.QLabel(self.guif_loginmenu)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.guif_lm_title_login.setFont(font)
        self.guif_lm_title_login.setAlignment(QtCore.Qt.AlignCenter)
        self.guif_lm_title_login.setObjectName("guif_lm_title_login")
        self.guif_lm_grid.addWidget(self.guif_lm_title_login, 1, 0, 1, 1)
        self.guif_lm_layout_btn = QtWidgets.QHBoxLayout()
        self.guif_lm_layout_btn.setObjectName("guif_lm_layout_btn")
        self.guif_lm_layout_btn_2 = QtWidgets.QGridLayout()
        self.guif_lm_layout_btn_2.setObjectName("guif_lm_layout_btn_2")
        self.guif_lm_lineEdit_user = QtWidgets.QLineEdit(self.guif_loginmenu)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.guif_lm_lineEdit_user.setFont(font)
        self.guif_lm_lineEdit_user.setMaxLength(32)
        self.guif_lm_lineEdit_user.setObjectName("guif_lm_lineEdit_user")
        self.guif_lm_layout_btn_2.addWidget(self.guif_lm_lineEdit_user, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.guif_lm_layout_btn_2.addItem(spacerItem6, 0, 3, 1, 1)
        self.guif_lm_label_pass = QtWidgets.QLabel(self.guif_loginmenu)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.guif_lm_label_pass.setFont(font)
        self.guif_lm_label_pass.setObjectName("guif_lm_label_pass")
        self.guif_lm_layout_btn_2.addWidget(self.guif_lm_label_pass, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.guif_lm_layout_btn_2.addItem(spacerItem7, 0, 0, 1, 1)
        self.guif_lm_label_user = QtWidgets.QLabel(self.guif_loginmenu)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.guif_lm_label_user.setFont(font)
        self.guif_lm_label_user.setObjectName("guif_lm_label_user")
        self.guif_lm_layout_btn_2.addWidget(self.guif_lm_label_user, 0, 1, 1, 1)
        self.guif_lm_lineEdit_pass = QtWidgets.QLineEdit(self.guif_loginmenu)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.guif_lm_lineEdit_pass.setFont(font)
        self.guif_lm_lineEdit_pass.setMaxLength(32)
        self.guif_lm_lineEdit_pass.setObjectName("guif_lm_lineEdit_pass")
        self.guif_lm_layout_btn_2.addWidget(self.guif_lm_lineEdit_pass, 1, 2, 1, 1)
        self.guif_lm_layout_btn.addLayout(self.guif_lm_layout_btn_2)
        self.guif_lm_grid.addLayout(self.guif_lm_layout_btn, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.guif_lm_grid.addItem(spacerItem8, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.guif_lm_grid, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem10, 2, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 1, 2, 1, 1)
        self.guif_mm_stacker.addWidget(self.guif_loginmenu)
        self.gridLayout_3.addWidget(self.guif_mm_stacker, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.guif_main_grid, 0, 0, 1, 1)
        guif_main.setCentralWidget(self.guif_main_wid)

        self.retranslateUi(guif_main)
        self.guif_mm_stacker.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(guif_main)

    def retranslateUi(self, guif_main):
        _translate = QtCore.QCoreApplication.translate
        guif_main.setWindowTitle(_translate("guif_main", "EduSuite"))
        self.guif_mm_btn_login.setText(_translate("guif_main", "  Login  "))
        self.guif_mm_btn_reg.setText(_translate("guif_main", "Register"))
        self.guif_mm_title.setText(_translate("guif_main", "EduSuite"))
        self.guif_lm_title_logo.setText(_translate("guif_main", "EduSuite"))
        self.guif_lm_title_login.setText(_translate("guif_main", "Login"))
        self.guif_lm_label_pass.setText(_translate("guif_main", "Password:"))
        self.guif_lm_label_user.setText(_translate("guif_main", "Username:"))
        
    def call_logmenu(self):
        self.guif_mm_stacker.setCurrentIndex(1)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guif_main = QtWidgets.QMainWindow()
    ui = Ui_guif_main()
    ui.setupUi(guif_main)
    guif_main.show()
    sys.exit(app.exec_())

